name: MIRAI Learn Daily
on:
  workflow_dispatch:
  schedule: [ { cron: '0 0 * * *' } ]   # JST 9時
jobs:
  train:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - name: Run training
        shell: pwsh
        run: python .\scripts\learn_task.py
      - uses: actions/upload-artifact@v4
        with: { name: learn-artifacts, path: artifacts/, if-no-files-found: ignore }