name: MIRAI Learn Daily
on:
  workflow_dispatch:
  schedule: [ { cron: '0 0 * * *' } ]   # JST 9時
jobs:
  train:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v4
      - name: Install Portable Python 3.10
        shell: pwsh
        run: |
          \ = 'https://www.python.org/ftp/python/3.10.11/python-3.10.11-embed-amd64.zip'
          \ = "\\py.zip"
          Invoke-WebRequest -Uri \ -OutFile \
          \ = "\\py310"
          New-Item -ItemType Directory -Force -Path \ | Out-Null
          Expand-Archive -Path \ -DestinationPath \ -Force
          (Get-Content "\\python310._pth") -replace '#import site','import site' | Set-Content "\\python310._pth"
          Add-Content \ "PY=\"
      - name: Run training
        shell: pwsh
        run: |
          & "\\python.exe" .\scripts\learn_task.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with: { name: learn-artifacts, path: artifacts/, if-no-files-found: ignore }