name: MIRAI OSS Sync
on:
  workflow_dispatch:
  push: { branches: [main] }
  schedule: [ { cron: '0 * * * *' } ]   # 毎時
jobs:
  run:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v4
      - name: Install Portable Python 3.10
        shell: powershell
        run: |
          \ = 'https://www.python.org/ftp/python/3.10.11/python-3.10.11-embed-amd64.zip'
          \ = "\\py.zip"
          Invoke-WebRequest -Uri \ -OutFile \
          \ = "\\py310"
          New-Item -ItemType Directory -Force -Path \ | Out-Null
          Expand-Archive -Path \ -DestinationPath \ -Force
          (Get-Content "\\python310._pth") -replace '#import site','import site' | Set-Content "\\python310._pth"
          "PY=\" | Out-File -FilePath \ -Append -Encoding utf8
      - name: Run OSS sync
        shell: powershell
        run: |
          & "\\python.exe" .\scripts\oss_sync.py
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with: { name: oss-sync-logs, path: logs/, if-no-files-found: ignore }