      - name: Notify (Discord or Slack)
        if: always()
        shell: powershell
        env:
          WEBHOOK: ${{ secrets.NOTIFY_WEBHOOK }}
          STATUS: ${{ job.status }}
        run: |
          $ok  = $env:STATUS -eq 'success'
          $wf  = $env:GITHUB_WORKFLOW
          $ttl = if ($ok) { "✅ $wf 成功" } else { "❌ $wf 失敗" }

          $lines = @(
            $ttl
            "repo: $env:GITHUB_REPOSITORY"
            "run : $env:GITHUB_RUN_NUMBER"
            "url : $env:GITHUB_SERVER_URL/$env:GITHUB_REPOSITORY/actions/runs/$env:GITHUB_RUN_ID"
          )
          $text = ($lines -join "`n")

          try {
            $payload = @{ content = $text } | ConvertTo-Json -Depth 3    # Discord
            Invoke-RestMethod -Uri $env:WEBHOOK -Method Post -ContentType 'application/json' -Body $payload -ErrorAction Stop
          } catch {
            $payload = @{ text = $text } | ConvertTo-Json -Depth 3       # Slack
            Invoke-RestMethod -Uri $env:WEBHOOK -Method Post -ContentType 'application/json' -Body $payload
          }
