name: Mirai Runner
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo Test
        run: echo "Mirai Runner is working!"
